version: '3'

services:
  gva-client:
    image: nginx:alpine
    container_name: gva-client-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - gva-network

networks:
  gva-network:
    driver: bridge

